export function patch(html){
const rep=(a,b)=>{if(!html.includes(a))throw new Error("patch-miss:"+a.slice(0,50));html=html.replace(a,b)};
rep("와일드카드 시리즈에서는 세인트루이스 카디널스를 2승 1패로 꺾고 디비전 시리즈에 진출해 필라델피아 필리스를 상대하게 됐다.","와일드카드 시리즈에서는 세인트루이스 카디널스를 2승 1패로 꺾었다. 이어 NLDS에서 필라델피아 필리스를 3승 무패로 스윕했고, NLCS에서는 뉴욕 메츠를 4승 2패로 제압해 2년 연속 월드시리즈에 진출했다. 월드시리즈 상대는 토론토 블루제이스다.");
rep("콜로라도는 86승 76패로 지구 2위·와일드카드에 진출한 뒤 세인트루이스를 2승 1패로 꺾고 NLDS에 올랐다.","콜로라도는 86승 76패로 지구 2위·와일드카드에 진출한 뒤 세인트루이스를 2승 1패, 필라델피아를 3승 무패, 뉴욕 메츠를 4승 2패로 차례로 제압해 월드시리즈에 진출했다.");
rep("67경기 2승 3패 52세이브, ERA 1.22, WAR 2.4. 첫 28경기 무실점으로 출발했고, 다저스전 3연속 세이브로 통산 300세이브를 달성했다. 콜로라도는 86승 76패로 지구 2위·와일드카드에 진출한 뒤 세인트루이스 카디널스를 2승 1패로 꺾고 NLDS에 진출했다.","67경기 2승 3패 52세이브, ERA 1.22, WAR 2.4. 첫 28경기 무실점으로 출발했고, 다저스전 3연속 세이브로 통산 300세이브를 달성했다. 콜로라도는 86승 76패로 지구 2위·와일드카드에 진출한 뒤 세인트루이스, 필라델피아, 뉴욕 메츠를 차례로 꺾고 2년 연속 월드시리즈에 진출했다.");
const old=html.match(/<section class="section" id="season-2033-postseason">.*?<\/section><section class="section" id="season-2033-season-games">/s);if(!old)throw new Error("postseason section");
rep(old[0],`<section class="section" id="season-2033-postseason"><h2>4. 포스트시즌<span class="edit">[편집]</span></h2>
<h3>4.1. 와일드카드 시리즈 vs 세인트루이스 카디널스</h3><p>콜로라도는 1차전을 내준 뒤 2·3차전을 연달아 잡아 2승 1패로 시리즈를 뒤집었다.</p><p>2차전에서 박은 2점 차 리드를 안고 등판해 <b>K-F9-F8</b>로 세 타자를 모두 범타 처리하며 1이닝 퍼펙트 세이브를 기록했다.</p>
<h3>4.2. NLDS vs 필라델피아 필리스</h3><p>콜로라도는 <b>5-0, 11-0, 7-2</b>로 3경기를 모두 잡아 3승 무패 스윕으로 NLCS에 진출했다.</p><p>1차전에서 박은 8회말 2사, 2점 차 리드 상황에 등판했다. 첫 타자를 좌익수 뜬공(F7)으로 처리해 8회를 끝낸 뒤 9회에도 <b>F8-F7-K</b>로 세 타자를 막아 <b>1⅓이닝 무실점 1탈삼진, 세이브</b>를 기록했다.</p>
<h3>4.3. NLCS vs 뉴욕 메츠</h3><p>콜로라도는 1차전 2-4 패배, 2차전 10-6 승리, 3차전 승리, 4차전 1-3 패배, 5차전 승리, 6차전 5-0 승리로 <b>4승 2패</b>를 기록해 월드시리즈에 진출했다.</p><p>3차전에서 박은 9회말 7-5 리드 상황에 등판해 4-3, F8로 두 타자를 처리한 뒤 솔로 홈런을 허용했지만 마지막 타자를 1-3으로 잡아 세이브를 올렸다. 기록은 <b>1이닝 1피안타 1자책 1피홈런, 1세이브</b>.</p><p>5차전에서는 6-3 리드 상황에 등판해 첫 타자에게 솔로 홈런을 허용했으나 이후 P2-K-K로 정리했다. 기록은 <b>1이닝 1피안타 1자책 1피홈런 2탈삼진, 1세이브</b>.</p>
<h3>4.4. 월드시리즈 vs 토론토 블루제이스</h3><p>콜로라도는 2년 연속 월드시리즈에 진출했다. 상대는 토론토 블루제이스다.</p><p>현재까지 세부 경기 결과는 기록되지 않았다.</p>
<div class="note"><b>2033 포스트시즌 현재 확인된 박의 등판:</b> 4경기 · 4세이브 · 4⅓이닝 · 2피안타 · 2자책 · 2피홈런 · 0볼넷 · 4탈삼진 · ERA 4.15 · WHIP 0.46</div></section><section class="section" id="season-2033-season-games">`);
rep('<tr><td>올스타</td><td style="text-align:left;white-space:normal"><a class="wikilink" data-doc-link="games" href="#games">2033 올스타 선정 · 전체 득표 1위</a>',`<tr><td>NLDS</td><td style="text-align:left;white-space:normal"><a class="wikilink" data-doc-link="games" href="#games">vs 필라델피아 · 3승 무패 스윕</a><br/><small>1차전 박 1⅓이닝 무실점 세이브 · F7 / F8 · F7 · K</small></td></tr><tr><td>NLCS</td><td style="text-align:left;white-space:normal"><a class="wikilink" data-doc-link="games" href="#games">vs 뉴욕 메츠 · 4승 2패</a><br/><small>박 3차전·5차전 세이브 · 두 경기 모두 솔로 홈런 1개씩 허용</small></td></tr><tr><td>월드시리즈</td><td style="text-align:left;white-space:normal"><a class="wikilink" data-doc-link="games" href="#games">vs 토론토 블루제이스</a><br/><small>2년 연속 월드시리즈 진출</small></td></tr><tr><td>올스타</td><td style="text-align:left;white-space:normal"><a class="wikilink" data-doc-link="games" href="#games">2033 올스타 선정 · 전체 득표 1위</a>`);
const at=html.indexOf('<article class="game-card" data-search="2033 와일드카드 세인트루이스');if(at<0)throw new Error("game insert");
const cards=`<article class="game-card" data-search="2033 nlds 필라델피아 필리스 1차전 8회말 2아웃 2점차 f7 f8 f7 k 세이브 4아웃 1.1이닝" data-stage="포스트시즌" data-unique="1" data-year="2033"><div class="game-top"><div class="game-title">NLDS 1차전 vs 필라델피아</div><div><span class="tag special">SV</span><span class="tag special">4아웃 세이브</span></div></div><div class="special">★ 8회 2사부터 등판 · 1⅓이닝 무실점</div><div class="tablewrap"><table class="wiki"><tbody><tr><th>상황</th><td style="text-align:left;white-space:normal">8회말 2사 · 2점 차 리드</td></tr><tr><th>타자 결과</th><td style="text-align:left;white-space:normal">F7 / F8 · F7 · K</td></tr><tr><th>박 기록</th><td style="text-align:left;white-space:normal">1⅓이닝 · 0피안타 · 0실점 · 0볼넷 · 1탈삼진 · 1세이브</td></tr></tbody></table></div></article>
<article class="game-card" data-search="2033 nlds 필라델피아 필리스 3승 무패 스윕 5대0 11대0 7대2 nlcs 진출 메츠" data-stage="포스트시즌" data-unique="1" data-year="2033"><div class="game-top"><div class="game-title">NLDS vs 필라델피아 · 3승 무패</div><div><span class="tag special">스윕</span><span class="tag special">NLCS 진출</span></div></div><div class="special">★ 5-0 · 11-0 · 7-2</div><div class="tablewrap"><table class="wiki"><tbody><tr><th>1차전</th><td>5-0 승리</td></tr><tr><th>2차전</th><td>11-0 승리</td></tr><tr><th>3차전</th><td>7-2 승리</td></tr><tr><th>결과</th><td>콜로라도 3승 무패 · NLCS 진출</td></tr><tr><th>다음 상대</th><td>뉴욕 메츠</td></tr></tbody></table></div></article>
<article class="game-card" data-search="2033 nlcs 뉴욕 메츠 3차전 9회말 7대5 4-3 f8 hr 1-3 세이브" data-stage="포스트시즌" data-unique="1" data-year="2033"><div class="game-top"><div class="game-title">NLCS 3차전 vs 뉴욕 메츠</div><div><span class="tag special">SV</span><span class="tag special">솔로 HR 허용</span></div></div><div class="special">★ 7-5 리드에서 등판 · 마지막 아웃까지 리드 유지</div><div class="tablewrap"><table class="wiki"><tbody><tr><th>상황</th><td style="text-align:left;white-space:normal">9회말 · 7-5 리드</td></tr><tr><th>타자 결과</th><td style="text-align:left;white-space:normal">4-3 · F8 · HR(1ER) · 1-3</td></tr><tr><th>박 기록</th><td style="text-align:left;white-space:normal">1이닝 · 1피안타 · 1자책 · 1피홈런 · 0볼넷 · 0탈삼진 · 1세이브</td></tr></tbody></table></div></article>
<article class="game-card" data-search="2033 nlcs 뉴욕 메츠 5차전 6대3 hr p2 k k 세이브" data-stage="포스트시즌" data-unique="1" data-year="2033"><div class="game-top"><div class="game-title">NLCS 5차전 vs 뉴욕 메츠</div><div><span class="tag special">SV</span><span class="tag special">2K</span></div></div><div class="special">★ 선두타자 솔로 HR 허용 후 P2-K-K</div><div class="tablewrap"><table class="wiki"><tbody><tr><th>상황</th><td style="text-align:left;white-space:normal">9회 · 6-3 리드</td></tr><tr><th>타자 결과</th><td style="text-align:left;white-space:normal">HR(1ER) · P2 · K · K</td></tr><tr><th>박 기록</th><td style="text-align:left;white-space:normal">1이닝 · 1피안타 · 1자책 · 1피홈런 · 0볼넷 · 2탈삼진 · 1세이브</td></tr></tbody></table></div></article>
<article class="game-card" data-search="2033 nlcs 뉴욕 메츠 4승2패 1차전2대4 2차전10대6 3차전승리 4차전1대3 5차전승리 6차전5대0 월드시리즈 토론토" data-stage="포스트시즌" data-unique="1" data-year="2033"><div class="game-top"><div class="game-title">NLCS vs 뉴욕 메츠 · 4승 2패</div><div><span class="tag special">NL 우승</span><span class="tag special">WS 진출</span></div></div><div class="special">★ 2년 연속 월드시리즈 진출 · 상대 토론토</div><div class="tablewrap"><table class="wiki"><tbody><tr><th>1차전</th><td>2-4 패배</td></tr><tr><th>2차전</th><td>10-6 승리</td></tr><tr><th>3차전</th><td>승리 · 박 세이브</td></tr><tr><th>4차전</th><td>1-3 패배</td></tr><tr><th>5차전</th><td>승리 · 박 세이브</td></tr><tr><th>6차전</th><td>5-0 승리</td></tr><tr><th>결과</th><td>콜로라도 4승 2패 · 월드시리즈 진출</td></tr><tr><th>월드시리즈 상대</th><td>토론토 블루제이스</td></tr></tbody></table></div></article>`;
html=html.slice(0,at)+cards+html.slice(at);
rep('<div class="notice"><b>수록 기준:</b> 당시 대화에 경기 단위로 보존된 기록만 수록한다. 누락된 실제 등판은 임의로 복원하지 않는다. 2032 포스트시즌은 팀의 모든 경기 결과가 보존되어 있어 미등판 경기까지 포함한다.</div>','<div class="notice"><b>수록 기준:</b> 경기별 세부 기록이 확인되는 등판과 주요 시리즈 결과를 중심으로 정리한다.</div>');
rep('Phillip Park 개인 위키 · v12.0 · 2033 NLDS 진출 · 경기 로그 54건','Phillip Park 개인 위키 · v13.0 · 2033 월드시리즈 진출 · 경기 로그 59건');
return html;
}